-- This script was generated by a beta version of the ERD tool in pgAdmin 4.
-- Please log an issue at https://redmine.postgresql.org/projects/pgadmin4/issues/new if you find any bugs, including reproduction steps.
BEGIN;


CREATE TABLE IF NOT EXISTS public.bridgedata
(
    uid text COLLATE pg_catalog."default" NOT NULL,
    username text COLLATE pg_catalog."default" NOT NULL,
    objdata json,
    CONSTRAINT bridgedata_pkey PRIMARY KEY (uid)
    );

CREATE TABLE IF NOT EXISTS public."gamedata-Lundaki"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-Lundaki_pkey" PRIMARY KEY ("timestamp")
    );

CREATE TABLE IF NOT EXISTS public."gamedata-The9axel5"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-The9axel5_pkey" PRIMARY KEY ("timestamp")
    );

CREATE TABLE IF NOT EXISTS public."gamedata-TheGTRacer97"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-TheGTRacer97_pkey" PRIMARY KEY ("timestamp")
    );

CREATE TABLE IF NOT EXISTS public."gamedata-akabox218"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-akabox218_pkey1" PRIMARY KEY ("timestamp")
    );

CREATE TABLE IF NOT EXISTS public."gamedata-hakipi"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-hakipi_pkey" PRIMARY KEY ("timestamp")
    );

CREATE TABLE IF NOT EXISTS public."gamedata-master"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-akabox218_pkey" PRIMARY KEY ("timestamp")
    );

CREATE TABLE IF NOT EXISTS public."gamedata-terpko"
(
    "timestamp" text COLLATE pg_catalog."default" NOT NULL,
    timeindex text COLLATE pg_catalog."default",
    playername text COLLATE pg_catalog."default",
    gamedata jsonb,
    CONSTRAINT "gamedata-terpko_pkey" PRIMARY KEY ("timestamp")
    );
END;
